extends:
  - airbnb
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:testing-library/recommended
  - plugin:jest-dom/recommended
  - prettier # must go last, to turn off some previous rules

plugins:
  - prefer-arrow
  - jest
  - jest-dom
  - testing-library

env:
  browser: true
  jest: true

parserOptions:
  ecmaVersion: 2020
  sourceType: module

rules:
  require-await: error
  prefer-arrow-callback: error
  prefer-arrow/prefer-arrow-functions: error
  react/forbid-prop-types: off
  react/react-in-jsx-scope: off
  react/prop-types: off
  react/jsx-filename-extension: off
  react/jsx-props-no-spreading: off
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - '**/*.test.tsx'
        - '**/*.spec.tsx'
        - '**/*test*'
  import/extensions: off
